// app/(routes)/games/mall-orca/page.tsx
import React from 'react';

const MallOrcaGamePage = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold mb-4">MALL-ORCA</h1>
      <p className="text-xl text-muted-foreground mb-6">
        A Low-Poly Adventure with a Twist of Truth.
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">Game Concept</h2>
        <p className="mb-4">
          MALL-ORCA is an envisioned game project set to be developed with a distinctive low-poly art style.
          While details about the core gameplay are still taking shape, a unique aspect of MALL-ORCA
          is its proposed integration of a system to address and highlight "fake news" or misinformation
          within the game world or its surrounding community features.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">Key Proposed Features</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>Low-Poly Art Style:</strong> A visually appealing and accessible aesthetic that is
            efficient for development and offers a unique charm.
          </li>
          <li>
            <strong>Fake News Kennzeichnung (Identification):</strong> A core mechanic or feature where
            misinformation or "fake news" encountered in the game or on its platform is clearly marked.
          </li>
          <li>
            <strong>Transparency in Information:</strong> While the creator of fake news might not see it flagged
            on their end, it would be visible to all other players, promoting media literacy and critical thinking.
          </li>
          <li>
            <strong>Player Anonymity (with caveats):</strong> The game aims to allow player anonymity, though this
            would be subject to legal review, especially concerning content generated by entities acting as
            businesses.
          </li>
          <li>
            <strong>Potential Themes:</strong> The name "MALL-ORCA" could hint at various themes – perhaps commercial environments
            (mall) mixed with natural or unexpected elements (orca). This could lead to interesting narrative
            or gameplay scenarios, possibly involving social commentary or exploration of consumerism versus nature.
            (Creative interpretation based on name).
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">Development & Funding</h2>
        <p>
          The project is currently in the conceptual stage, with plans for development and seeking funding
          to bring its unique vision to life. It represents an innovative approach to gaming by not just
          providing entertainment, but also by subtly encouraging players to think critically about the
          information they consume.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-3">Why MALL-ORCA?</h2>
        <p>
          In an era of information overload, MALL-ORCA stands out by proposing to weave elements of media
          awareness into its fabric. It's a game that could spark conversations and offer a playful yet
          meaningful take on navigating the complexities of the digital age.
        </p>
      </section>
    </div>
  );
};

export default MallOrcaGamePage;
