name: Auto-assign PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          assignees: BjarneNiklas 