name: Suggest labels for new issues

on:
  issues:
    types: [opened]

jobs:
  suggest-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Suggest labels
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👉 **Tipp:** Bitte wähle passende Labels wie `bug`, `feature`, `backend`, `frontend` für eine schnellere Bearbeitung!"
            }) 